[workspace]
members = [
#    "sender-eframe", # trying eframe/egui
    "receiver",
    "shared",
#    "sender-tauri/sender/src-tauri" # trying tauri
]
resolver = "2"

[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = true
debug = false
panic = "abort"